aspring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        title: Imperator Admin
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Imperator Admin</span>
      notify:
        mail:
          to: starrier@starrier.org
          enabled: true
          from: starrier@starrier.org
      discovery:
        enabled: true
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  mail:
    host: smtp.qq.com
    username: starrier@starrier.org
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    consul:
      host: 118.25.141.149
      port: 8500
      discovery:
        service-name: imperator-admin
        health-check-interval: 10s
        tags: admin
        health-check-path: /actuator/health
        register-health-check: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    consul:
      enabled=false:
